### ISSUE TITLE
Add possibility to actually download videos

### ISSUE THREAD

**Issue by jens1o** [GyrosOfWar/youtube-dl-rs#1]
Hey,

thanks for your time! I appreciate it and especially that it is Free Software, the data extraction part with all the metadata is especially useful. I was wondering whether we could - apart from that - run youtube_dl and actually save the video to a given location.

Cheers!

**Comment by GyrosOfWar** [comment]
Hi! 
I'm surprised someone actually found this crate! To your question, I don't see why that wouldn't be possible. I imagine the easiest solution would be to add a second terminating operation on the `YoutubeDl` builder:
```rust
YoutubeDl::new("https://www.youtube.com/watch?v=VFbhKZFzbzk")
  .download("/path/to/video,mp4")?;
```

I might get around to it on the weekend, but I'd be happy to review a PR for this feature if you want to start it in the meanwhile.

**Comment by jens1o** [comment]
Thanks for your reply! I understand your concerns about the limitations, yet in the end it is your decision whether to ship or not ship that feature. :)

If you opt for having this, I can take a look for an implementation. In the meantime, I'll just manually implement it. :)

**Comment by ticky** [comment]
> edit: Actually, thinking about this a little more, I'm not sure if doing the download via youtube-dl directly is the best idea. It's really hard to handle errors properly, you have very little control (you can't watch its progress, it's hard to tell from the outside whether the process hangs or just takes long etc.). In a lot of cases, you can just point a Rust HTTP client library of your choice (e.g. `reqwest`) to the URL you get from the JSON and download the file yourself.

That approach doesn't really work for downloading formats which YouTube-dl or yt-dlp would remux into a combined format, which include m3u8 playlists (Twitch) and YouTube videos in higher resolution formats.

**Comment by GyrosOfWar** [comment]
> That approach doesn't really work for downloading formats which YouTube-dl or yt-dlp would remux into a combined format, which include m3u8 playlists (Twitch) and YouTube videos in higher resolution formats.

That's a good point! I'll put it on my to-dos.

**Comment by ticky** [comment]
I've attempted working around it with `--no-simulate` in the extra arguments but I then get a JSON parsing panic, so I might have a patch in my near future to help with that end of things, haha ☺️

**Comment by GyrosOfWar** [comment]
Interesting. I've never really tried that. I'd be happy to accept contributions as well, obviously.

**Comment by ticky** [comment]
Ah, I think `--no-simulate` is a `yt-dlp`-specific option.

I get this error:

`Json(Error("expected value", line: 1, column: 3))`

And having run `yt-dlp` with and without `--no-simulate`, the difference is primarily video/subtitle download URL tokens, but there is this lone set of field differences which I suspect might be causing the issue (the JSON has been pretty-printed for easier diffing):

```diff
--- no-simulate.txt	2022-02-07 11:38:31.000000000 -0800
+++ simulate.txt	2022-02-07 11:38:28.000000000 -0800
@@ -5450,14 +5450,9 @@
                     "acodec": "mp4a.40.2",
                     "abr": 129.478,
                     "asr": 44100,
-                    "epoch": 1644262608,
+                    "epoch": 1644262616,
                     "_filename": "Everyone Should do this Simple $10 Car Mod [QWkUFkXcx9I].mp4",
-                    "__postprocessors":
-                    [],
-                    "__real_download": false,
-                    "__finaldir": "/Users/ticky/Downloads",
-                    "filepath": "/Users/ticky/Downloads/Everyone Should do this Simple $10 Car Mod [QWkUFkXcx9I].mp4",
-                    "__write_download_archive": true
+                    "__write_download_archive": false
                 }
             ],
             "requested_formats":
```

I'm not finding any references to any of these seemingly-internal values being used by `youtube-dl-rs`, any thoughts on what the problem might be?

**Comment by GyrosOfWar** [comment]
Ok, so currently the library is tryting to parse the progress information that `yt-dlp` prints out (`[download] 100% of 37.48MiB in 00:0`). I guess `yt-dlp` outputs this on `stdout` as well? That's kind of unfortunate.

**Comment by ticky** [comment]
Oh, that *is* an unfortunate choice with JSON output enabled, but it might just magically work with `--no-progress` added in that case. I imagine my tests were invalid because it was seeing the pipe to a file and *not* doing that.

**Comment by ticky** [comment]
Yeah, `--no-progress` is a workaround which suits my need right now, though progress reporting of some kind _would_ be helpful. Savvy use of `--progress-template` and `--newline` might be the way to go for that
