### ISSUE TITLE
Parsing error on timestamp value

### ISSUE THREAD

**Issue by laBecasse** [GyrosOfWar/youtube-dl-rs#15]
Hello, thanks for the project ! 

I got an error on this link : https://www.reddit.com/r/loopdaddy/comments/baguqq/first_time_poster_here_couldnt_resist_sharing_my
```
Failed with: json error: invalid type: floating point `1554647898`, expected i64
```

I discovered that it comes from "timestamp" using the following command line: 
```
youtube-dl -J https://www.reddit.com/r/loopdaddy/comments/baguqq/first_time_poster_here_couldnt_resist_sharing_my | jq . | grep "1554647898" 
```

**Comment by GyrosOfWar** [comment]
Hi, thanks for letting me know! It works when I change the type of `timestamp` to `Option<f64>`, but storing a Unix timestamp as a floating point makes me kind of uncomfortable. I'll see if I maybe write some custom parsing code or just chnage it to a float.

**Comment by twiclo** [comment]
This works with `yt-dlp` and the `yt-dlp` feature enabled. I must once again advocate for dropping `youtube-dl` as [they don't plan on supporting anything newer than python 3.2](https://github.com/ytdl-org/youtube-dl/issues/30568). This library will only get more polluted if we want to support legacy software

**Comment by stefnotch** [comment]
Considering that youtube-dl has not gotten any updates in months, I think it'd be fair to exclusively support yt-dlp.

Even the youtubedl subreddit is apparently doing the switch, notice how the pinned posts are all about yt-dlp https://www.reddit.com/r/youtubedl/

**Comment by GyrosOfWar** [comment]
I have now reworked the library to only support yt-dlp since youtube-dl seems to not have a lot of activity lately. If it picks up again, I'm definitely open to re-adding support behind a feature flag or a runtime switch (if that's feasible).
