### ISSUE TITLE
Adding epoch time to yt-dlp feature

### ISSUE THREAD

**Issue by twiclo** [GyrosOfWar/youtube-dl-rs#21]
I've been trying to figure out how to add a field in the json-dump of yt-dlp called `epoch`. I've added it to `JsonOutput` and `SingleVideo`. I've also tried adding the `#[cfg(feature = "yt-dlp")]` above each epoch line to see if that would help. The epoch field just gets set to a `None`. What am I missing here?

**Comment by GyrosOfWar** [comment]
Hey, can you maybe post (a gist) of the JSON dump where the `epoch` field is set? That would make it easier to debug.

**Comment by twiclo** [comment]
The problem is that `yt-dlp` isn't actually ran when using the the feature. I will likely submit a PR for this soon

**Comment by twiclo** [comment]
https://github.com/GyrosOfWar/youtube-dl-rs/pull/22
