### ISSUE TITLE
Tests Fail When Run Inside Docker Container

### ISSUE THREAD

**Issue by beyse** [GyrosOfWar/youtube-dl-rs#36]
#### Issue description

I want to use the crate inside a minimal docker container but the tests of this crate fail. 

This also leads to a problem in other projects like [this](https://github.com/DvorakDwarf/Infinite-Storage-Glitch/issues/62) issue.

#### Steps to reproduce the issue

To reproduce you need docker installed in your machine.

1. Clone [this](https://github.com/beyse/youtube-dl-rs) fork I created for this purpose: `git clone https://github.com/beyse/youtube-dl-rs.git`
2. Build the docker image: `docker build -t yt .`
3. Run a shell in the docker container: `docker run -it --rm -v ${PWD}:/home/youtube-dl-rs yt /bin/bash`
4. You are now in the container, so you can build the project using `cargo build`
5. Once that is done run the tests: `cargo test`

#### What's the expected result?

I would expect all tests to pass ✅ 

#### What's the actual result?

7 / 8 tests fail ❌ 

#### Additional details / screenshot

![image](https://user-images.githubusercontent.com/5306790/221658915-fee514e9-b777-4520-bacd-1917fb9f6e64.png)

**Comment by GyrosOfWar** [comment]
Hi, yeah, the tests require yt-dlp to be installed. See also the GitHub action file [here](https://github.com/GyrosOfWar/youtube-dl-rs/blob/master/.github/workflows/ci.yml) (this one installs youtube-dl as well, but that's no longer necessary).

**Comment by beyse** [comment]
Alright, so I added pip and pip installed yt-dlp in my Dockerfile [here](https://github.com/GyrosOfWar/youtube-dl-rs/commit/d56ec061a5e03d1f8e951bdd8fc1338252aef8f7) and can confirm all tests pass ✅.

Thank you for your help @GyrosOfWar
