### ISSUE TITLE
json error: invalid type: integer `2`, expected a string

### ISSUE THREAD

**Issue by phiresky** [GyrosOfWar/youtube-dl-rs#9]
This is caused by the `season_number` member:

`youtube-dl -j 'sAD1nayZ9dk'`

![image](https://user-images.githubusercontent.com/2303841/111004516-7dd80780-8389-11eb-867b-6ff683694f34.png)

**Comment by GyrosOfWar** [comment]
Thanks for the report, I'll fix this shortly.

**Comment by GyrosOfWar** [comment]
Fixed and published as 0.6.1: https://crates.io/crates/youtube_dl/0.6.1
